# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gwatch_v3-2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.help_autoMot2 = QtWidgets.QPushButton(self.tab)
        self.help_autoMot2.setObjectName("help_autoMot2")
        self.gridLayout.addWidget(self.help_autoMot2, 0, 5, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 4)
        self.help_directory = QtWidgets.QPushButton(self.tab)
        self.help_directory.setObjectName("help_directory")
        self.gridLayout.addWidget(self.help_directory, 1, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 4)
        self.help_watch_fn = QtWidgets.QPushButton(self.tab)
        self.help_watch_fn.setObjectName("help_watch_fn")
        self.gridLayout.addWidget(self.help_watch_fn, 3, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 4, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.tab)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 4, 2, 1, 3)
        self.help_num_of_fra = QtWidgets.QPushButton(self.tab)
        self.help_num_of_fra.setObjectName("help_num_of_fra")
        self.gridLayout.addWidget(self.help_num_of_fra, 4, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 5, 1, 1, 4)
        self.help_do_gain = QtWidgets.QPushButton(self.tab)
        self.help_do_gain.setObjectName("help_do_gain")
        self.gridLayout.addWidget(self.help_do_gain, 5, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 6, 1, 1, 3)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 6, 4, 1, 1)
        self.help_gain_name = QtWidgets.QPushButton(self.tab)
        self.help_gain_name.setObjectName("help_gain_name")
        self.gridLayout.addWidget(self.help_gain_name, 6, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 7, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 7, 1, 1, 4)
        self.help_do_gain_2 = QtWidgets.QPushButton(self.tab)
        self.help_do_gain_2.setObjectName("help_do_gain_2")
        self.gridLayout.addWidget(self.help_do_gain_2, 7, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 8, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 8, 1, 1, 3)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 8, 4, 1, 1)
        self.help_gain_name_2 = QtWidgets.QPushButton(self.tab)
        self.help_gain_name_2.setObjectName("help_gain_name_2")
        self.gridLayout.addWidget(self.help_gain_name_2, 8, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 10, 0, 1, 5)
        self.help_option = QtWidgets.QPushButton(self.tab)
        self.help_option.setObjectName("help_option")
        self.gridLayout.addWidget(self.help_option, 10, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 11, 2, 1, 1)
        self.checkBox_0 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_0.setObjectName("checkBox_0")
        self.gridLayout.addWidget(self.checkBox_0, 11, 3, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout.addWidget(self.checkBox_1, 11, 4, 1, 1)
        self.help_option_2 = QtWidgets.QPushButton(self.tab)
        self.help_option_2.setObjectName("help_option_2")
        self.gridLayout.addWidget(self.help_option_2, 11, 5, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 12, 3, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 12, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 13, 0, 1, 3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 13, 3, 1, 2)
        self.help_pixsize = QtWidgets.QPushButton(self.tab)
        self.help_pixsize.setObjectName("help_pixsize")
        self.gridLayout.addWidget(self.help_pixsize, 13, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 14, 0, 1, 3)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 14, 3, 1, 2)
        self.help_pixsize_2 = QtWidgets.QPushButton(self.tab)
        self.help_pixsize_2.setObjectName("help_pixsize_2")
        self.gridLayout.addWidget(self.help_pixsize_2, 14, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 15, 0, 1, 3)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 15, 3, 1, 2)
        self.help_pixsize_3 = QtWidgets.QPushButton(self.tab)
        self.help_pixsize_3.setObjectName("help_pixsize_3")
        self.gridLayout.addWidget(self.help_pixsize_3, 15, 5, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 16, 0, 1, 2)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 17, 0, 1, 5)
        self.help_option_3 = QtWidgets.QPushButton(self.tab)
        self.help_option_3.setObjectName("help_option_3")
        self.gridLayout.addWidget(self.help_option_3, 17, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.help_pixsize_4 = QtWidgets.QPushButton(self.tab_2)
        self.help_pixsize_4.setObjectName("help_pixsize_4")
        self.gridLayout_2.addWidget(self.help_pixsize_4, 4, 2, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 3, 1, 1, 1)
        self.help_do_eva = QtWidgets.QPushButton(self.tab_2)
        self.help_do_eva.setObjectName("help_do_eva")
        self.gridLayout_2.addWidget(self.help_do_eva, 1, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 5, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 5, 1, 1, 1)
        self.help_pixsize_6 = QtWidgets.QPushButton(self.tab_2)
        self.help_pixsize_6.setObjectName("help_pixsize_6")
        self.gridLayout_2.addWidget(self.help_pixsize_6, 5, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 6, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 7, 0, 1, 2)
        self.help_option_4 = QtWidgets.QPushButton(self.tab_2)
        self.help_option_4.setObjectName("help_option_4")
        self.gridLayout_2.addWidget(self.help_option_4, 7, 2, 1, 1)
        self.help_autoEva = QtWidgets.QPushButton(self.tab_2)
        self.help_autoEva.setObjectName("help_autoEva")
        self.gridLayout_2.addWidget(self.help_autoEva, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 8, 0, 1, 1)
        self.help_do_eva_2 = QtWidgets.QPushButton(self.tab_2)
        self.help_do_eva_2.setObjectName("help_do_eva_2")
        self.gridLayout_2.addWidget(self.help_do_eva_2, 2, 2, 1, 1)
        self.help_pixsize_5 = QtWidgets.QPushButton(self.tab_2)
        self.help_pixsize_5.setObjectName("help_pixsize_5")
        self.gridLayout_2.addWidget(self.help_pixsize_5, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setStyleSheet("")
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_5.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setStyleSheet("")
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 2, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_5.addWidget(self.textBrowser_2, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 4, 0, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_5.addWidget(self.textBrowser_3, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        #self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok) 
        self.buttonBoxOK = self.buttonBox.addButton("&Run",QtWidgets.QDialogButtonBox.ActionRole)
        self.buttonBoxCancel = self.buttonBox.addButton("&Cancel",QtWidgets.QDialogButtonBox.RejectRole)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())
        self.label_3.setBuddy(self.lineEdit)
        self.label_4.setBuddy(self.lineEdit_2)
        self.label_5.setBuddy(self.comboBox)
        self.label_6.setBuddy(self.lineEdit_3)
        self.label_19.setBuddy(self.comboBox)
        self.label_20.setBuddy(self.lineEdit_3)
        self.label_7.setBuddy(self.lineEdit_4)
        self.label_16.setBuddy(self.lineEdit_4)
        self.label_10.setBuddy(self.lineEdit_5)
        self.label_11.setBuddy(self.lineEdit_6)
        self.label_12.setBuddy(self.lineEdit_7)
        self.label_17.setBuddy(self.lineEdit_4)
        self.label_2.setBuddy(self.pushButton)
        self.label_14.setBuddy(self.lineEdit_9)
        self.label_13.setBuddy(self.lineEdit_8)
        self.label_15.setBuddy(self.lineEdit_8)
        self.label_18.setBuddy(self.comboBox_2)
        self.label_21.setBuddy(self.lineEdit_4)
        self.label_9.setBuddy(self.comboBox_2)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.help_directory)
        MainWindow.setTabOrder(self.help_directory, self.help_autoMot2)
        MainWindow.setTabOrder(self.help_autoMot2, self.help_watch_fn)
        MainWindow.setTabOrder(self.help_watch_fn, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.horizontalSlider)
        MainWindow.setTabOrder(self.horizontalSlider, self.help_num_of_fra)
        MainWindow.setTabOrder(self.help_num_of_fra, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.help_do_gain)
        MainWindow.setTabOrder(self.help_do_gain, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.help_gain_name)
        MainWindow.setTabOrder(self.help_gain_name, self.comboBox_4)
        MainWindow.setTabOrder(self.comboBox_4, self.help_do_gain_2)
        MainWindow.setTabOrder(self.help_do_gain_2, self.lineEdit_11)
        MainWindow.setTabOrder(self.lineEdit_11, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.help_gain_name_2)
        MainWindow.setTabOrder(self.help_gain_name_2, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.help_option)
        MainWindow.setTabOrder(self.help_option, self.checkBox_0)
        MainWindow.setTabOrder(self.checkBox_0, self.checkBox_1)
        MainWindow.setTabOrder(self.checkBox_1, self.help_option_2)
        MainWindow.setTabOrder(self.help_option_2, self.checkBox_2)
        MainWindow.setTabOrder(self.checkBox_2, self.checkBox_3)
        MainWindow.setTabOrder(self.checkBox_3, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.help_pixsize)
        MainWindow.setTabOrder(self.help_pixsize, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.help_pixsize_2)
        MainWindow.setTabOrder(self.help_pixsize_2, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.help_pixsize_3)
        MainWindow.setTabOrder(self.help_pixsize_3, self.lineEdit_12)
        MainWindow.setTabOrder(self.lineEdit_12, self.help_option_3)
        MainWindow.setTabOrder(self.help_option_3, self.help_pixsize_4)
        MainWindow.setTabOrder(self.help_pixsize_4, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.help_do_eva)
        MainWindow.setTabOrder(self.help_do_eva, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.lineEdit_10)
        MainWindow.setTabOrder(self.lineEdit_10, self.help_pixsize_6)
        MainWindow.setTabOrder(self.help_pixsize_6, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.lineEdit_13)
        MainWindow.setTabOrder(self.lineEdit_13, self.help_option_4)
        MainWindow.setTabOrder(self.help_option_4, self.help_autoEva)
        MainWindow.setTabOrder(self.help_autoEva, self.help_do_eva_2)
        MainWindow.setTabOrder(self.help_do_eva_2, self.help_pixsize_5)
        MainWindow.setTabOrder(self.help_pixsize_5, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.textBrowser_2)
        MainWindow.setTabOrder(self.textBrowser_2, self.buttonBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gwatch"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Automatic MotionCor2</span></p></body></html>"))
        self.help_autoMot2.setText(_translate("MainWindow", "?"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.help_directory.setText(_translate("MainWindow", "?"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Watching File Name:</span></p></body></html>"))
        self.help_watch_fn.setText(_translate("MainWindow", "?"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Number of Frame:</span></p></body></html>"))
        self.help_num_of_fra.setText(_translate("MainWindow", "?"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Do Gain-Reference?:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Yes"))
        self.comboBox.setItemText(1, _translate("MainWindow", "No"))
        self.help_do_gain.setText(_translate("MainWindow", "?"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Name of Gain-Reference:</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Browse"))
        self.help_gain_name.setText(_translate("MainWindow", "?"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Do Measure Ice-thickness ratio?:</span></p></body></html>"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Yes"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "No"))
        self.help_do_gain_2.setText(_translate("MainWindow", "?"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Name of Image without energy filter:</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Browse"))
        self.help_gain_name_2.setText(_translate("MainWindow", "?"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Additional Option for MotionCor2:</p></body></html>"))
        self.help_option.setText(_translate("MainWindow", "?"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Which GPUs :</p></body></html>"))
        self.checkBox_0.setText(_translate("MainWindow", "GPU 0"))
        self.checkBox_1.setText(_translate("MainWindow", "GPU 1"))
        self.help_option_2.setText(_translate("MainWindow", "?"))
        self.checkBox_2.setText(_translate("MainWindow", "GPU 2"))
        self.checkBox_3.setText(_translate("MainWindow", "GPU 3"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Pixcel Size (A):</p></body></html>"))
        self.help_pixsize.setText(_translate("MainWindow", "?"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Cs (mm):</p></body></html>"))
        self.help_pixsize_2.setText(_translate("MainWindow", "?"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Acceleration Voltage (kV):</p></body></html>"))
        self.help_pixsize_3.setText(_translate("MainWindow", "?"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Additional Option for Gctf:</p></body></html>"))
        self.help_option_3.setText(_translate("MainWindow", "?"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Watching Directory:</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Automatic MotionCor2"))
        self.help_pixsize_4.setText(_translate("MainWindow", "?"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Yes"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "No"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">How many Micrographs use to calculate?:</p></body></html>"))
        self.help_do_eva.setText(_translate("MainWindow", "?"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Yes"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "No"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Particle Diameter (A):</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Binning:</p></body></html>"))
        self.help_pixsize_6.setText(_translate("MainWindow", "?"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Calculate 2D classification every batch?:</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Additional Option for 2D classification (Relion2):</p></body></html>"))
        self.help_option_4.setText(_translate("MainWindow", "?"))
        self.help_autoEva.setText(_translate("MainWindow", "?"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Automatic 2D-Classification</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Calculate 2D classification?:</span></p></body></html>"))
        self.help_do_eva_2.setText(_translate("MainWindow", "?"))
        self.help_pixsize_5.setText(_translate("MainWindow", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Automatic 2D-classification"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Results of MotionCor2 and Gctf</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Commands for Automatic 2D-Classification</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Results"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open Setting"))
        self.actionSave.setText(_translate("MainWindow", "Save Setting"))

